FROM python:3.11-slim
WORKDIR /app
COPY src/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ ./
COPY static/ ./static
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/src
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]