version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: plantcam-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: plantcam-postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD", "bash", "-c", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
